export const schemes = {
  AES: true,
  Blowfish: true,
  Camellia: true,
  ChaCha20: true,
  DES: true,
  DSA: true,
  ECDSA: true,
  ECC: true,
  ElGamal: true,
  FHE: true,
  GOST: true,
  HMAC: true,
  IDEA: true,
  MD5: true,
  RSA: true,
  Serpent: true,
  "SHA-1": true,
  "SHA-256": true,
  "Triple DES": true,
  Twofish: true,
  Whirlpool: true,
};
