export const infrastrutcures = {
  Akka: true,
  Ansible: true,
  "Apache Hadoop": true,
  "Apache Kafka": true,
  "Apache Mesos": true,
  "Apache Spark": true,
  "AWS CloudFormation": true,
  "AWS Elastic Beanstalk": true,
  "Azure Resource Manager": true,
  Chef: true,
  Consul: true,
  Docker: true,
  "Eclipse Vert.x": true,
  Elasticsearch: true,
  Etcd: true,
  Grafana: true,
  GraphQL: true,
  HAProxy: true,
  "HashiCorp Nomad": true,
  Helm: true,
  InfluxDB: true,
  Istio: true,
  Jenkins: true,
  Kubernetes: true,
  Linkerd: true,
  Logstash: true,
  "Mesosphere DC/OS": true,
  "Microsoft Azure": true,
  "Microsoft IIS": true,
  MongoDB: true,
  MySQL: true,
  Netty: true,
  Nginx: true,
  OpenStack: true,
  Packer: true,
  Prometheus: true,
  RabbitMQ: true,
  Redis: true,
  SaltStack: true,
  "Spring Boot": true,
  Terraform: true,
  Traefik: true,
  Vault: true,
  VirtualBox: true,
  "VMware vSphere": true,
  Vagrant: true,
  Zookeeper: true,
};
