export const databases = {
  "Amazon DynamoDB": true,
  "Apache Cassandra": true,
  "Apache HBase": true,
  "Apache Ignite": true,
  CockroachDB: true,
  Couchbase: true,
  DB2: true,
  Elasticsearch: true,
  Firebase: true,
  Greenplum: true,
  "Hadoop HDFS": true,
  Hive: true,
  "IBM Informix": true,
  InfluxDB: true,
  MariaDB: true,
  Memcached: true,
  "Microsoft Access": true,
  "Microsoft Azure Cosmos DB": true,
  "Microsoft SQL Server": true,
  MongoDB: true,
  MySQL: true,
  Neo4j: true,
  "Oracle Database": true,
  "Oracle NoSQL Database": true,
  Orion: true,
  Presto: true,
  PostgreSQL: true,
  RavenDB: true,
  Redis: true,
  "SAP HANA": true,
  Snowflake: true,
  SQLite: true,
  Teradata: true,
  TiDB: true,
  Vertica: true,
  VoltDB: true,
};
