export const games = {
  Unity: true,
  "Unreal Engine": true,
  Godot: true,
  Phaser: true,
  "Cocos2d-x": true,
  LibGDX: true,
  Construct: true,
  Monogame: true,
  PlayCanvas: true,
  Defold: true,
  "GameMaker Studio": true,
  "Corona SDK": true,
  LÖVE: true,
  MelonJS: true,
  Gideros: true,
  Panda3D: true,
  "Pixi.js": true,
  "Crafty.js": true,
  "Three.js": true,
  "Babylon.js": true,
};
