export const languages = {
  "1C Enterprise": true,
  "2-Dimensional Array": true,
  "4D": true,
  ABAP: true,
  "ABAP CDS": true,
  ABNF: true,
  "AGS Script": true,
  AIDL: true,
  AL: true,
  AMPL: true,
  ANTLR: true,
  "API Blueprint": true,
  APL: true,
  ASL: true,
  "ASN.1": true,
  "ASP.NET": true,
  ATS: true,
  ActionScript: true,
  Ada: true,
  "Adblock Filter List": true,
  "Adobe Font Metrics": true,
  Agda: true,
  Alloy: true,
  "Alpine Abuild": true,
  "Altium Designer": true,
  AngelScript: true,
  "Ant Build System": true,
  Antlers: true,
  ApacheConf: true,
  Apex: true,
  "Apollo Guidance Computer": true,
  AppleScript: true,
  Arc: true,
  AsciiDoc: true,
  AspectJ: true,
  Assembly: true,
  Astro: true,
  Asymptote: true,
  Augeas: true,
  AutoHotkey: true,
  AutoIt: true,
  "Avro IDL": true,
  Awk: true,
  BASIC: true,
  Ballerina: true,
  Batchfile: true,
  Beef: true,
  Befunge: true,
  Berry: true,
  BibTeX: true,
  Bicep: true,
  Bikeshed: true,
  Bison: true,
  BitBake: true,
  Blade: true,
  BlitzBasic: true,
  BlitzMax: true,
  Bluespec: true,
  Boo: true,
  Boogie: true,
  Brainfuck: true,
  BrighterScript: true,
  Brightscript: true,
  Browserslist: true,
  C: true,
  "C#": true,
  "C++": true,
  "C-ObjDump": true,
  "C2hs Haskell": true,
  "CAP CDS": true,
  CIL: true,
  CLIPS: true,
  CMake: true,
  COBOL: true,
  CODEOWNERS: true,
  COLLADA: true,
  CSON: true,
  CSS: true,
  CSV: true,
  CUE: true,
  CWeb: true,
  "Cabal Config": true,
  Cadence: true,
  Cairo: true,
  CameLIGO: true,
  "Cap'n Proto": true,
  CartoCSS: true,
  Ceylon: true,
  Chapel: true,
  Charity: true,
  Checksums: true,
  ChucK: true,
  Circom: true,
  Cirru: true,
  Clarion: true,
  Clarity: true,
  "Classic ASP": true,
  Clean: true,
  Click: true,
  Clojure: true,
  "Closure Templates": true,
  "Cloud Firestore Security Rules": true,
  "CoNLL-U": true,
  CodeQL: true,
  CoffeeScript: true,
  ColdFusion: true,
  "ColdFusion CFC": true,
  "Common Lisp": true,
  "Common Workflow Language": true,
  "Component Pascal": true,
  Cool: true,
  Coq: true,
  "Cpp-ObjDump": true,
  Creole: true,
  Crystal: true,
  Csound: true,
  "Csound Document": true,
  "Csound Score": true,
  Cuda: true,
  "Cue Sheet": true,
  Curry: true,
  Cycript: true,
  Cypher: true,
  Cython: true,
  D: true,
  "D-ObjDump": true,
  D2: true,
  "DIGITAL Command Language": true,
  DM: true,
  "DNS Zone": true,
  DTrace: true,
  Dafny: true,
  "Darcs Patch": true,
  Dart: true,
  DataWeave: true,
  "Debian Package Control File": true,
  DenizenScript: true,
  Dhall: true,
  Diff: true,
  "DirectX 3D File": true,
  Dockerfile: true,
  Dogescript: true,
  Dotenv: true,
  Dylan: true,
  E: true,
  "E-mail": true,
  EBNF: true,
  ECL: true,
  ECLiPSe: true,
  EJS: true,
  EQ: true,
  Eagle: true,
  Earthly: true,
  Easybuild: true,
  "Ecere Projects": true,
  Ecmarkup: true,
  EditorConfig: true,
  "Edje Data Collection": true,
  Eiffel: true,
  Elixir: true,
  Elm: true,
  Elvish: true,
  "Elvish Transcript": true,
  "Emacs Lisp": true,
  EmberScript: true,
  Erlang: true,
  Euphoria: true,
  "F#": true,
  "F*": true,
  "FIGlet Font": true,
  FLUX: true,
  Factor: true,
  Fancy: true,
  Fantom: true,
  Faust: true,
  Fennel: true,
  "Filebench WML": true,
  Filterscript: true,
  Fluent: true,
  Formatted: true,
  Forth: true,
  Fortran: true,
  "Fortran Free Form": true,
  FreeBasic: true,
  FreeMarker: true,
  Frege: true,
  Futhark: true,
  "G-code": true,
  GAML: true,
  GAMS: true,
  GAP: true,
  "GCC Machine Description": true,
  GDB: true,
  GDScript: true,
  GEDCOM: true,
  GLSL: true,
  GN: true,
  GSC: true,
  "Game Maker Language": true,
  "Gemfile.lock": true,
  Gemini: true,
  Genero: true,
  "Genero Forms": true,
  Genie: true,
  Genshi: true,
  "Gentoo Ebuild": true,
  "Gentoo Eclass": true,
  "Gerber Image": true,
  "Gettext Catalog": true,
  Gherkin: true,
  "Git Attributes": true,
  "Git Config": true,
  "Git Revision List": true,
  Gleam: true,
  Glyph: true,
  "Glyph Bitmap Distribution Format": true,
  Gnuplot: true,
  Go: true,
  "Go Checksums": true,
  "Go Module": true,
  "Go Workspace": true,
  "Godot Resource": true,
  Golo: true,
  Gosu: true,
  Grace: true,
  Gradle: true,
  "Grammatical Framework": true,
  "Graph Modeling Language": true,
  GraphQL: true,
  "Graphviz (DOT)": true,
  Groovy: true,
  "Groovy Server Pages": true,
  HAProxy: true,
  HCL: true,
  HLSL: true,
  HOCON: true,
  HTML: true,
  "HTML+ECR": true,
  "HTML+EEX": true,
  "HTML+ERB": true,
  "HTML+PHP": true,
  "HTML+Razor": true,
  HTTP: true,
  HXML: true,
  Hack: true,
  Haml: true,
  Handlebars: true,
  Harbour: true,
  Haskell: true,
  Haxe: true,
  HiveQL: true,
  HolyC: true,
  Hy: true,
  HyPhy: true,
  IDL: true,
  "IGOR Pro": true,
  INI: true,
  "IRC log": true,
  Idris: true,
  "Ignore List": true,
  "ImageJ Macro": true,
  Imba: true,
  "Inform 7": true,
  Ink: true,
  "Inno Setup": true,
  Io: true,
  Ioke: true,
  Isabelle: true,
  "Isabelle ROOT": true,
  J: true,
  "JAR Manifest": true,
  JCL: true,
  JFlex: true,
  JSON: true,
  "JSON with Comments": true,
  JSON5: true,
  JSONLD: true,
  JSONiq: true,
  Janet: true,
  Jasmin: true,
  Java: true,
  "Java Properties": true,
  "Java Server Pages": true,
  JavaScript: true,
  "JavaScript+ERB": true,
  "Jest Snapshot": true,
  "JetBrains MPS": true,
  Jinja: true,
  Jison: true,
  "Jison Lex": true,
  Jolie: true,
  Jsonnet: true,
  Julia: true,
  "Jupyter Notebook": true,
  Just: true,
  KRL: true,
  "Kaitai Struct": true,
  KakouneScript: true,
  KerboScript: true,
  "KiCad Layout": true,
  "KiCad Legacy Layout": true,
  "KiCad Schematic": true,
  Kickstart: true,
  Kit: true,
  Kotlin: true,
  Kusto: true,
  LFE: true,
  LLVM: true,
  LOLCODE: true,
  LSL: true,
  "LTspice Symbol": true,
  LabVIEW: true,
  Lark: true,
  Lasso: true,
  Latte: true,
  Lean: true,
  Less: true,
  Lex: true,
  LigoLANG: true,
  LilyPond: true,
  Limbo: true,
  "Linker Script": true,
  "Linux Kernel Module": true,
  Liquid: true,
  "Literate Agda": true,
  "Literate CoffeeScript": true,
  "Literate Haskell": true,
  LiveScript: true,
  Logos: true,
  Logtalk: true,
  LookML: true,
  LoomScript: true,
  Lua: true,
  M: true,
  M4: true,
  M4Sugar: true,
  MATLAB: true,
  MAXScript: true,
  MDX: true,
  MLIR: true,
  MQL4: true,
  MQL5: true,
  MTML: true,
  MUF: true,
  Macaulay2: true,
  Makefile: true,
  Mako: true,
  Markdown: true,
  Marko: true,
  Mask: true,
  Mathematica: true,
  "Maven POM": true,
  Max: true,
  Mercury: true,
  Mermaid: true,
  Meson: true,
  Metal: true,
  "Microsoft Developer Studio Project": true,
  "Microsoft Visual Studio Solution": true,
  MiniD: true,
  MiniYAML: true,
  Mint: true,
  Mirah: true,
  Modelica: true,
  "Modula-2": true,
  "Modula-3": true,
  "Module Management System": true,
  Monkey: true,
  "Monkey C": true,
  Moocode: true,
  MoonScript: true,
  Motoko: true,
  "Motorola 68K Assembly": true,
  Move: true,
  Muse: true,
  Mustache: true,
  Myghty: true,
  NASL: true,
  NCL: true,
  NEON: true,
  NL: true,
  "NPM Config": true,
  NSIS: true,
  NWScript: true,
  Nasal: true,
  Nearley: true,
  Nemerle: true,
  NetLinx: true,
  "NetLinx+ERB": true,
  NetLogo: true,
  NewLisp: true,
  Nextflow: true,
  Nginx: true,
  Nim: true,
  Ninja: true,
  Nit: true,
  Nix: true,
  Noir: true,
  Nu: true,
  NumPy: true,
  Nunjucks: true,
  Nushell: true,
  "OASv2-json": true,
  "OASv2-yaml": true,
  "OASv3-json": true,
  "OASv3-yaml": true,
  OCaml: true,
  ObjDump: true,
  "Object Data Instance Notation": true,
  ObjectScript: true,
  "Objective-C": true,
  "Objective-C++": true,
  "Objective-J": true,
  Odin: true,
  Omgrofl: true,
  Opa: true,
  Opal: true,
  "Open Policy Agent": true,
  "OpenAPI Specification v2": true,
  "OpenAPI Specification v3": true,
  OpenCL: true,
  "OpenEdge ABL": true,
  OpenQASM: true,
  "OpenRC runscript": true,
  OpenSCAD: true,
  "OpenStep Property List": true,
  "OpenType Feature File": true,
  "Option List": true,
  Org: true,
  Ox: true,
  Oxygene: true,
  Oz: true,
  P4: true,
  PDDL: true,
  "PEG.js": true,
  PHP: true,
  PLSQL: true,
  PLpgSQL: true,
  "POV-Ray SDL": true,
  Pact: true,
  Pan: true,
  Papyrus: true,
  Parrot: true,
  "Parrot Assembly": true,
  "Parrot Internal Representation": true,
  Pascal: true,
  Pawn: true,
  Pep8: true,
  Perl: true,
  Pic: true,
  Pickle: true,
  PicoLisp: true,
  PigLatin: true,
  Pike: true,
  PlantUML: true,
  Pod: true,
  "Pod 6": true,
  PogoScript: true,
  Polar: true,
  Pony: true,
  Portugol: true,
  PostCSS: true,
  PostScript: true,
  PowerBuilder: true,
  PowerShell: true,
  Prisma: true,
  Processing: true,
  Procfile: true,
  Proguard: true,
  Prolog: true,
  Promela: true,
  "Propeller Spin": true,
  "Protocol Buffer": true,
  "Protocol Buffer Text Format": true,
  "Public Key": true,
  Pug: true,
  Puppet: true,
  "Pure Data": true,
  PureBasic: true,
  PureScript: true,
  Pyret: true,
  Python: true,
  "Python console": true,
  "Python traceback": true,
  "Q#": true,
  QML: true,
  QMake: true,
  "Qt Script": true,
  Quake: true,
  R: true,
  RAML: true,
  RBS: true,
  RDoc: true,
  REALbasic: true,
  REXX: true,
  RMarkdown: true,
  RPC: true,
  RPGLE: true,
  "RPM Spec": true,
  RUNOFF: true,
  Racket: true,
  Ragel: true,
  Raku: true,
  Rascal: true,
  "Raw token data": true,
  ReScript: true,
  "Readline Config": true,
  Reason: true,
  ReasonLIGO: true,
  Rebol: true,
  "Record Jar": true,
  Red: true,
  Redcode: true,
  "Redirect Rules": true,
  "Regular Expression": true,
  "Ren'Py": true,
  RenderScript: true,
  "Rich Text Format": true,
  Ring: true,
  Riot: true,
  RobotFramework: true,
  Roff: true,
  "Roff Manpage": true,
  Rouge: true,
  "RouterOS Script": true,
  Ruby: true,
  Rust: true,
  SAS: true,
  SCSS: true,
  "SELinux Policy": true,
  SMT: true,
  SPARQL: true,
  SQF: true,
  SQL: true,
  SQLPL: true,
  "SRecode Template": true,
  "SSH Config": true,
  STAR: true,
  STL: true,
  STON: true,
  SVG: true,
  SWIG: true,
  Sage: true,
  SaltStack: true,
  Sass: true,
  Scala: true,
  Scaml: true,
  Scenic: true,
  Scheme: true,
  Scilab: true,
  Self: true,
  ShaderLab: true,
  Shell: true,
  "ShellCheck Config": true,
  ShellSession: true,
  Shen: true,
  Sieve: true,
  "Simple File Verification": true,
  Singularity: true,
  Slash: true,
  Slice: true,
  Slim: true,
  SmPL: true,
  Smali: true,
  Smalltalk: true,
  Smarty: true,
  Smithy: true,
  Snakemake: true,
  Solidity: true,
  Soong: true,
  SourcePawn: true,
  "Spline Font Database": true,
  Squirrel: true,
  Stan: true,
  "Standard ML": true,
  Starlark: true,
  Stata: true,
  StringTemplate: true,
  Stylus: true,
  "SubRip Text": true,
  SugarSS: true,
  SuperCollider: true,
  Svelte: true,
  Sway: true,
  Swift: true,
  SystemVerilog: true,
  "TI Program": true,
  "TL-Verilog": true,
  TLA: true,
  TOML: true,
  TSQL: true,
  TSV: true,
  TSX: true,
  TXL: true,
  Talon: true,
  Tcl: true,
  Tcsh: true,
  TeX: true,
  Tea: true,
  Terra: true,
  Texinfo: true,
  Text: true,
  "TextMate Properties": true,
  Textile: true,
  Thrift: true,
  Turing: true,
  Turtle: true,
  Twig: true,
  "Type Language": true,
  TypeScript: true,
  "Unified Parallel C": true,
  "Unity3D Asset": true,
  "Unix Assembly": true,
  Uno: true,
  UnrealScript: true,
  UrWeb: true,
  V: true,
  VBA: true,
  VBScript: true,
  VCL: true,
  VHDL: true,
  Vala: true,
  "Valve Data Format": true,
  "Velocity Template Language": true,
  Verilog: true,
  "Vim Help File": true,
  "Vim Script": true,
  "Vim Snippet": true,
  "Visual Basic .NET": true,
  "Visual Basic 6.0": true,
  Volt: true,
  Vue: true,
  Vyper: true,
  WDL: true,
  "Wavefront Material": true,
  "Wavefront Object": true,
  "Web Ontology Language": true,
  WebAssembly: true,
  "WebAssembly Interface Type": true,
  WebIDL: true,
  WebVTT: true,
  "Wget Config": true,
  Whiley: true,
  Wikitext: true,
  "Win32 Message File": true,
  "Windows Registry Entries": true,
  "Witcher Script": true,
  Wollok: true,
  "World of Warcraft Addon Data": true,
  Wren: true,
  "X BitMap": true,
  "X Font Directory Index": true,
  "X PixMap": true,
  X10: true,
  XC: true,
  XCompose: true,
  XML: true,
  "XML Property List": true,
  XPages: true,
  XProc: true,
  XQuery: true,
  XS: true,
  XSLT: true,
  Xojo: true,
  Xonsh: true,
  Xtend: true,
  YAML: true,
  YANG: true,
  YARA: true,
  YASnippet: true,
  Yacc: true,
  Yul: true,
  ZAP: true,
  ZIL: true,
  Zeek: true,
  ZenScript: true,
  Zephir: true,
  Zig: true,
  Zimpl: true,
  "cURL Config": true,
  desktop: true,
  dircolors: true,
  eC: true,
  edn: true,
  fish: true,
  hoon: true,
  jq: true,
  kvlang: true,
  "mIRC Script": true,
  mcfunction: true,
  mupad: true,
  nanorc: true,
  nesC: true,
  ooc: true,
  q: true,
  reStructuredText: true,
  "robots.txt": true,
  sed: true,
  wisp: true,
  xBase: true,
};
