import { RESSOURCE_TAGS } from "src/api/ressource-tags";

export const BILLING_PROFILES_TAGS = {
  all: [RESSOURCE_TAGS.BILLING_PROFILES],
  me: [RESSOURCE_TAGS.ME, RESSOURCE_TAGS.BILLING_PROFILES],
};
