name: Migrations run

description: Install Diesel CLI and run migrations

runs:
  using: "composite"
  steps:
    - name: Install diesel CLI
      shell: bash
      run: cargo install diesel_cli@2.1.0 --no-default-features --features postgres

    - name: Run migrations
      shell: bash
      run: cd backend && diesel migration run
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost/marketplace_db
