export enum ApiResourcePaths {
  GET_USER = "/api/v1/me",
  GET_ALL_PROJECTS = "/api/v1/projects",
  GET_PROJECT_DETAILS = "/api/v1/projects/{{id}}",
  GET_PROJECT_DETAILS_SLUG = "/api/v1/projects/slug/{{id}}",
  GET_PROJECT_CONTRIBUTORS = "/api/v1/projects/{{id}}/contributors",
  GET_MY_PAYOUT_INFO = "/api/v1/me/payout-info",
  GET_MY_REWARDS = "/api/v1/me/rewards",
  GET_MY_REWARD_BY_ID = "/api/v1/me/rewards/{{id}}",
  GET_MY_REWARD_ITEMS_BY_ID = "/api/v1/me/rewards/{{id}}/reward-items",
  GET_MY_REWARDS_AMOUNTS = "/api/v1/me/rewards/amounts",
  GET_MY_REWARDS_PENDING_INVOICE = "/api/v1/me/rewards/pending-invoice",
  GET_PROJECT_REWARDS_LIST = "/api/v1/projects/{{id}}/rewards",
  PROJECT_REWARD = "/api/v1/projects/{{projectId}}/rewards/{{rewardId}}",
  GET_PAYOUT_INFO = "/api/v1/me/payout-info",
  GET_PUBLIC_USER_PROFILE = "/api/v1/users/{{id}}",
  GET_PUBLIC_USER_PROFILE_BY_LOGIN = "/api/v1/users/login/{{id}}",
  GET_USER_PROFILE = "/api/v1/me",
  GET_PROJECT_REWARD_ITEMS = "/api/v1/projects/{{projectId}}/rewards/{{rewardId}}/reward-items",
}
