export const frameworks = {
  DeFi: true,
  Ethereum: true,
  Hardhat: true,
  "Hyperledger Fabric": true,
  Lisk: true,
  NEM: true,
  NEO: true,
  Nile: true,
  Protostar: true,
  Quorum: true,
  Ripple: true,
  Stellar: true,
  Substrate: true,
  Tezos: true,
  Truffle: true,
  "RISC Zero zkVM": true,
};
