export const frameworks = {
  Angular: true,
  "ASP.NET": true,
  "ASP.NET Core": true,
  "Backbone.js": true,
  Bootstrap: true,
  CakePHP: true,
  Django: true,
  "Ember.js": true,
  "Express.js": true,
  Flask: true,
  Flutter: true,
  Gatsby: true,
  Grails: true,
  Hibernate: true,
  Ionic: true,
  JavaFX: true,
  jQuery: true,
  "Koa.js": true,
  Laravel: true,
  Meteor: true,
  "Next.js": true,
  "Node.js": true,
  Phoenix: true,
  Play: true,
  Polymer: true,
  Pyramid: true,
  Rails: true,
  React: true,
  "React Native": true,
  RubyMotion: true,
  "Ruby on Rails": true,
  "Sails.js": true,
  Spring: true,
  "Spring Boot": true,
  Symfony: true,
  Tailwind: true,
  Thymeleaf: true,
  Tkinter: true,
  Tornado: true,
  "Vue.js": true,
  Wagtail: true,
  Web2py: true,
  Webix: true,
  Webpack: true,
  WooCommerce: true,
  WordPress: true,
  Xamarin: true,
  Yii: true,
  "Zend Framework": true,
};
