export const protocols = {
  AJP: true,
  BGP: true,
  CIFS: true,
  CoAP: true,
  DHCP: true,
  DNS: true,
  DTLS: true,
  EIGRP: true,
  FTP: true,
  Gopher: true,
  GRE: true,
  HTTP: true,
  HTTPS: true,
  ICMP: true,
  ICMPv6: true,
  IGMP: true,
  IMAP: true,
  IP: true,
  IPsec: true,
  "IS-IS": true,
  LDAP: true,
  LLDP: true,
  L2TP: true,
  MPLS: true,
  MQTT: true,
  NAT: true,
  NetBIOS: true,
  NFS: true,
  NTP: true,
  OSPF: true,
  POP3: true,
  PPTP: true,
  RDP: true,
  RIP: true,
  RTP: true,
  RTSP: true,
  SFTP: true,
  SIP: true,
  SMTP: true,
  SNMP: true,
  SSH: true,
  SSL: true,
  TCP: true,
  TLS: true,
  Telnet: true,
  TFTP: true,
  VoIP: true,
  WebSocket: true,
  WPA: true,
  XMPP: true,
};

export const authenticationProtocols = {
  Kerberos: true,
  OAuth: true,
  OpenID: true,
  "OpenID Connect": true,
  PAP: true,
  RADIUS: true,
  SAML: true,
};
