CREATE TABLE EVENTS (
    INDEX SERIAL PRIMARY KEY,
    TIMESTAMP TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    AGGREGATE_NAME VARCHAR NOT NULL,
    AGGREGATE_ID VARCHAR NOT NULL,
    PAYLOAD JSON NOT NULL
)
