// Generated by ChatGPT, if you're not happy with it, see that with him
import { Octokit } from "@octokit/rest";
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

async function main() {
  const { payload } = JSON.parse(process.env.GITHUB_EVENT);

  if (payload.action !== "opened" && payload.action !== "synchronize") {
    return;
  }

  const { number, base, head, repository } = payload.pull_request;

  const { data: comparison } = await octokit.rest.repos.compareCommits({
    owner: repository.owner.login,
    repo: repository.name,
    base: base.sha,
    head: head.sha,
  });

  const specificFilePatterns = [/^\.env\.example$/, /^docker-compose.yml$/, /Procfile$/, /app\.yml$/];

  const filesChanged = comparison.files
    .filter(file => specificFilePatterns.some(pattern => pattern.test(file.filename)))
    .map(file => file.filename)
    .join(", ");

  if (filesChanged) {
    const comment = `The following specific files have been changed: ${filesChanged}.

Confirm that you have:

[] updated environment variables in staging
[] updated environment variables in production
[] done any required change in Heroku (new dynos, new apps, etc.)`;

    await octokit.rest.issues.createComment({
      owner: repository.owner.login,
      repo: repository.name,
      issue_number: number,
      body: comment,
    });
  }
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
