export enum ACTIONS_RESSOURCES {
  ME = "ME",
  REWARDS = "REWARDS",
  PROJECTS = "PROJECTS",
  GITHUB = "GITHUB",
  USERS = "USERS",
  TECHNOLOGIES = "TECHNOLOGIES",
  BILLING_PROFILES = "BILLING_PROFILES",
}
