export const LOCAL_STORAGE_JOINING_REASON_KEY = "joiningReason";

export const USER_PROFILE_JOINING_REASON_CONTRIBUTOR = "CONTRIBUTOR";
export const USER_PROFILE_JOINING_REASON_MAINTAINER = "MAINTAINER";
export const USER_PROFILE_JOINING_REASON_SPONSOR = "SPONSOR";
