default:
  amqp:
    connection_retry_interval_ms: 6000
    connection_retry_count: 100
  coinmarketcap:
    api_key: $COINMARKETCAP_API_KEY
    currencies:
      USD: "2781"
      ETH: "1027"
      OP: "11840"
      APT: "21794"
  database:
    url: $DATABASE_URL
    pool_max_size: 3
  github_api_client:
    base_url: $GITHUB_BASE_URL
    personal_access_tokens: $GITHUB_PAT
    max_calls_per_request: $GITHUB_MAX_CALLS_PER_REQUEST
  dusty_bot_api_client:
    base_url: $DUSTY_BOT_GITHUB_BASE_URL
    personal_access_tokens: $DUSTY_BOT_GITHUB_PAT
    max_calls_per_request: $DUSTY_BOT_GITHUB_MAX_CALLS_PER_REQUEST
  graphql_client:
    base_url: $GRAPHQL_BASE_URL
    headers:
      x-hasura-admin-secret: $HASURA_GRAPHQL_ADMIN_SECRET
  http:
    api_keys:
      - $BACKEND_GRAPHQL_API_KEY
  indexer_client:
    base_url: $GITHUB_INDEXER_BASE_URL
    headers:
      api-key: $GITHUB_INDEXER_API_KEY
  new_indexer_client:
    base_url: $INDEXER_BASE_URL
    headers:
      api-key: $INDEXER_API_KEY
  s3:
    images_bucket_name: onlydust-app-images
    bucket_region: eu-west-1
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
  web3:
    url: https://mainnet.infura.io/v3/$INFURA_API_KEY

local:
  amqp:
    url: $AMQP_URL
  tracer:
    json: false
    ansi: true
    location: true

production:
  amqp:
    url: $CLOUDAMQP_URL
  tracer:
    json: true
    ansi: false
    location: true
